#!/usr/bin/env dart

import 'dart:io';

void main() {
  // Paths to the pubspec.yaml files
  final mcpPubspecPath = 'packages/marionette_mcp/pubspec.yaml';
  final flutterPubspecPath = 'packages/marionette_flutter/pubspec.yaml';
  final outputPath = 'packages/marionette_mcp/lib/src/version.g.dart';

  // Read and parse versions
  final mcpVersion = extractVersion(mcpPubspecPath);
  final flutterVersion = extractVersion(flutterPubspecPath);

  print('marionette_mcp version: $mcpVersion');
  print('marionette_flutter version: $flutterVersion');

  // Check if versions match
  if (mcpVersion != flutterVersion) {
    stderr.writeln(
      'ERROR: Version mismatch!\n'
      '  marionette_mcp: $mcpVersion\n'
      '  marionette_flutter: $flutterVersion\n'
      'Both packages must have the same version.',
    );
    exit(1);
  }

  // Generate version.g.dart
  final generatedContent = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_version.dart

const version = '$mcpVersion';
''';

  final outputFile = File(outputPath);
  outputFile.writeAsStringSync(generatedContent);

  print('Generated $outputPath with version: $mcpVersion');
}

String extractVersion(String pubspecPath) {
  final file = File(pubspecPath);
  
  if (!file.existsSync()) {
    stderr.writeln('ERROR: File not found: $pubspecPath');
    exit(1);
  }

  final content = file.readAsStringSync();
  final lines = content.split('\n');

  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.startsWith('version:')) {
      // Extract version after 'version:'
      final version = trimmed.substring('version:'.length).trim();
      if (version.isEmpty) {
        stderr.writeln('ERROR: Empty version in $pubspecPath');
        exit(1);
      }
      return version;
    }
  }

  stderr.writeln('ERROR: Version not found in $pubspecPath');
  exit(1);
}
