#!/usr/bin/env dart

import 'dart:io';

void main() {
  // Paths to the pubspec.yaml files
  final mcpPubspecPath = 'packages/marionette_mcp/pubspec.yaml';
  final flutterPubspecPath = 'packages/marionette_flutter/pubspec.yaml';
  final outputPath = 'packages/marionette_mcp/lib/src/version.g.dart';

  // Read and parse versions
  final mcpVersion = extractVersion(mcpPubspecPath);
  final flutterVersion = extractVersion(flutterPubspecPath);

  print('marionette_mcp version: $mcpVersion');
  print('marionette_flutter version: $flutterVersion');

  // Check if versions match
  if (mcpVersion != flutterVersion) {
    stderr.writeln(
      'ERROR: Version mismatch!\n'
      '  marionette_mcp: $mcpVersion\n'
      '  marionette_flutter: $flutterVersion\n'
      'Both packages must have the same version.',
    );
    exit(1);
  }

  // Validate version format (semantic versioning)
  if (!isValidVersion(mcpVersion)) {
    stderr.writeln(
      'ERROR: Invalid version format: $mcpVersion\n'
      'Version must follow semantic versioning (e.g., 1.0.0, 0.2.3, 1.2.3-beta)',
    );
    exit(1);
  }

  // Generate version.g.dart
  final generatedContent = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_version.dart

const version = '$mcpVersion';
''';

  final outputFile = File(outputPath);
  // Ensure the directory exists
  outputFile.parent.createSync(recursive: true);
  outputFile.writeAsStringSync(generatedContent);

  print('Generated $outputPath with version: $mcpVersion');
}

String extractVersion(String pubspecPath) {
  final file = File(pubspecPath);
  
  if (!file.existsSync()) {
    stderr.writeln('ERROR: File not found: $pubspecPath');
    exit(1);
  }

  final content = file.readAsStringSync();
  final lines = content.split('\n');

  for (final line in lines) {
    final trimmed = line.trim();
    // Match 'version:' at the start of the line (accounting for leading spaces)
    if (trimmed.startsWith('version:')) {
      // Extract version after 'version:', removing quotes if present
      var version = trimmed.substring('version:'.length).trim();
      
      // Remove surrounding quotes if present
      if ((version.startsWith('"') && version.endsWith('"')) ||
          (version.startsWith("'") && version.endsWith("'"))) {
        version = version.substring(1, version.length - 1);
      }
      
      if (version.isEmpty) {
        stderr.writeln('ERROR: Empty version in $pubspecPath');
        exit(1);
      }
      return version;
    }
  }

  stderr.writeln('ERROR: Version not found in $pubspecPath');
  exit(1);
}

bool isValidVersion(String version) {
  // Basic semantic versioning pattern: major.minor.patch with optional pre-release and build metadata
  // Examples: 1.0.0, 0.2.3, 1.2.3-beta, 1.0.0+build123, 1.2.3-alpha.1+build.456
  final semverPattern = RegExp(
    r'^\d+\.\d+\.\d+(-[0-9A-Za-z\-\.]+)?(\+[0-9A-Za-z\-\.]+)?$',
  );
  return semverPattern.hasMatch(version);
}
